#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

xcode-select -p >/dev/null 2>&1 || {
  echo "Couldn't find Xcode command line tools!"
  echo "Run \`xcode-select --install\` before trying to bootstrap this project again."
  exit 1
}

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems
  }
fi

# delete Gemfile.lock - we always want the latest and greatest
rm -f Gemfile.lock
